-- =================================================================
-- IBBS PROTOTYPE DATABASE DUMP
-- Generated by Antigravity
-- =================================================================

DROP DATABASE IF EXISTS IBBS_PROTOTYPE;
CREATE DATABASE IBBS_PROTOTYPE;
USE IBBS_PROTOTYPE;

-- 1. USERS TABLE
CREATE TABLE users (
    user_id INT(11) NOT NULL AUTO_INCREMENT,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone_number VARCHAR(15) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('PASSENGER','ADMIN','AGENT') DEFAULT 'PASSENGER',
    created_at TIMESTAMP NOT NULL DEFAULT current_timestamp(),
    PRIMARY KEY (user_id)
);

-- 2. DRIVERS TABLE
CREATE TABLE drivers (
    driver_id INT(11) NOT NULL AUTO_INCREMENT,
    national_id VARCHAR(20) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    PRIMARY KEY (driver_id)
);

-- 3. BUSES TABLE
CREATE TABLE buses (
    bus_id INT(11) NOT NULL AUTO_INCREMENT,
    reg_no VARCHAR(20) NOT NULL UNIQUE,
    bus_name VARCHAR(50) DEFAULT NULL,
    max_passengers INT(11) NOT NULL,
    seat_layout VARCHAR(20) NOT NULL,
    driver_id INT(11) DEFAULT NULL,
    PRIMARY KEY (bus_id),
    FOREIGN KEY (driver_id) REFERENCES drivers (driver_id) ON DELETE SET NULL
);

-- 4. ROUTES TABLE
CREATE TABLE routes (
    route_id INT(11) NOT NULL AUTO_INCREMENT,
    from_location VARCHAR(100) NOT NULL,
    to_location VARCHAR(100) NOT NULL,
    departure_date DATE NOT NULL,
    departure_time TIME NOT NULL,
    cost DECIMAL(10,2) NOT NULL,
    bus_id INT(11) NOT NULL,
    status ENUM('SCHEDULED','COMPLETED','CANCELLED') DEFAULT 'SCHEDULED',
    PRIMARY KEY (route_id),
    FOREIGN KEY (bus_id) REFERENCES buses (bus_id)
);

-- 5. BOOKINGS TABLE
CREATE TABLE bookings (
    booking_id INT(11) NOT NULL AUTO_INCREMENT,
    booking_time DATETIME NOT NULL DEFAULT current_timestamp(),
    seat_number VARCHAR(10) NOT NULL,
    booking_status ENUM('CONFIRMED','CANCELLED','PAID','CHECKED_IN') DEFAULT 'PAID',
    qr_token VARCHAR(255) DEFAULT NULL,
    user_id INT(11) NOT NULL,
    route_id INT(11) NOT NULL,
    bus_id INT(11) NOT NULL,
    passenger_name VARCHAR(255) NOT NULL DEFAULT '',
    passenger_age INT(11) NOT NULL DEFAULT 0,
    passenger_id_number VARCHAR(50) NOT NULL DEFAULT '',
    PRIMARY KEY (booking_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id),
    FOREIGN KEY (route_id) REFERENCES routes (route_id) ON DELETE CASCADE,
    FOREIGN KEY (bus_id) REFERENCES buses (bus_id),
    UNIQUE KEY unique_booking (route_id, seat_number)
);

-- 6. FEEDBACK TABLE
CREATE TABLE feedback (
    feedback_id INT(11) NOT NULL AUTO_INCREMENT,
    rating INT(11) DEFAULT 5,
    comments TEXT NOT NULL,
    feedback_date DATE NOT NULL,
    user_id INT(11) NOT NULL,
    bus_id INT(11) NOT NULL,
    route_id INT(11) NOT NULL,
    submitted_at TIMESTAMP NOT NULL DEFAULT current_timestamp(),
    PRIMARY KEY (feedback_id),
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY (bus_id) REFERENCES buses (bus_id),
    FOREIGN KEY (route_id) REFERENCES routes (route_id) ON DELETE CASCADE
);

-- =================================================================
-- DATA INSERTION
-- =================================================================

-- Inserting ADMIN Users
INSERT INTO users (first_name, last_name, email, phone_number, password, role) VALUES 
('Alice', 'Kamau', 'alice1@gmail.com', '0700000000', '$2y$10$6AP9mQLbsAlcc2yDxdX3.Oed376Faioz4iG2NG7Z5ZTsEOQU8huQe', 'ADMIN'),
('Bob', 'Ochieng', 'bob2@gmail.com', '0700000001', '$2y$10$eOws.VlRQIGeg7axR6s9pOcAEHNSQ7ogTbPqG4uGzsnXQJ1jf2GUK', 'ADMIN'),
('Charlie', 'Kipkorir', 'charlie3@gmail.com', '0700000002', '$2y$10$nnpgJAAK5jr6CwCNQbFJTuRXCZZY017LneYwnjbpX2IhOa1aHKZqW', 'ADMIN'),
('David', 'Maina', 'david4@gmail.com', '0700000003', '$2y$10$KPSYO2TIhGX2uVCcycR08uyYkqVoQMnq7t1xWLGIP0j8d5Hhz7y32', 'ADMIN'),
('Eve', 'Wanjiku', 'eve5@gmail.com', '0700000004', '$2y$10$07KWtn7qvTnlWR4AWJprzujaiG4W0QuNot90mOJaD61jwkIHcBOVS', 'ADMIN'),
('Frank', 'Otieno', 'frank6@gmail.com', '0700000005', '$2y$10$Dw4bGCBQoh6he42VVOKyqegyTzNd81KDtP8J0hg3r79pAOfZWll/e', 'ADMIN'),
('Grace', 'Achieng', 'grace7@gmail.com', '0700000006', '$2y$10$Kf8pw34A0CbitzLb2W1uhOrJuy3Jpz8YaBkHZnFrCGUEWvToaukuC', 'ADMIN'),
('Hank', 'Musyoka', 'hank8@gmail.com', '0700000007', '$2y$10$7AfpBfCzt0V0ID.iVXutLOdQjeT6YfQQTz7toR776amoEqHSKpApK', 'ADMIN'),
('Ivy', 'Njeri', 'ivy9@gmail.com', '0700000008', '$2y$10$l7XO37p6M77kIXQmFT/7au5acAaWJyqXPueFCs6QEDK2rT7iAE10u', 'ADMIN'),
('Jack', 'Mutua', 'jack10@gmail.com', '0700000009', '$2y$10$faynGAGhm8/w.YVgf42B1eSL7Kta9AdKvGCSz93ZfhT/Oge6Wu2Z2', 'ADMIN');

-- Inserting AGENT Users
INSERT INTO users (first_name, last_name, email, phone_number, password, role) VALUES 
('Karen', 'Njoroge', 'karen1@gmail.com', '0711000000', '$2y$10$vorDX2PZQq6CNyKhnEd6muNccbOp0/kAsmf/VoOvsdL9VixyFckha', 'AGENT'),
('Leo', 'Mwangi', 'leo2@gmail.com', '0711000001', '$2y$10$n63JIZe9OeTTLHSgl9HrEuSQsam528/xT2XNpUo/jhNka2HVBWrYK', 'AGENT'),
('Mia', 'Odhiambo', 'mia3@gmail.com', '0711000002', '$2y$10$e2UZmFWu0tvbMmaWdt/vtObHNqAnVEaY3JuZL2q6rKn9gDYQWXcPW', 'AGENT'),
('Noah', 'Kimani', 'noah4@gmail.com', '0711000003', '$2y$10$OtaT8IBKXLzF7TwwxVjmpe8UyX7iXI2a991g2Bnf7BUbt4tjApzMu', 'AGENT'),
('Olivia', 'Chebet', 'olivia5@gmail.com', '0711000004', '$2y$10$Vajn3ZpLHhurmfDz/CsvluQznpN7kTYjjk.Dxl9ktS4VJt9SicYmm', 'AGENT'),
('Paul', 'Kariuki', 'paul6@gmail.com', '0711000005', '$2y$10$QTQGUhYKwJv9krYSEI/sku0vRIsACDQ2eE3FD3Ac07/b8tYf2C9m6', 'AGENT'),
('Quinn', 'Awere', 'quinn7@gmail.com', '0711000006', '$2y$10$LntrFhaxjyTKyGEShGKFsuY/j7E5McloZPjzKoDRDozZjMmnaRjqS', 'AGENT'),
('Ryan', 'Omondi', 'ryan8@gmail.com', '0711000007', '$2y$10$/Y6W3rm6Ug1L5sWVHCeQn.QwOFX0brsk7jyUpxNXLus.aayOwA1SO', 'AGENT'),
('Sarah', 'Wambui', 'sarah9@gmail.com', '0711000008', '$2y$10$ZTnq0FaW5YapQmPJCahjredJ3fs.VlquxaIxWfSQhS7u82DBdGBOK', 'AGENT'),
('Tom', 'Ndegwa', 'tom10@gmail.com', '0711000009', '$2y$10$0L.4AyomYevMyybNyBoGue4ZEUqn8I1S..h8MV7jyyx1Mi5sW3S5G', 'AGENT');

-- Inserting PASSENGER Users
INSERT INTO users (first_name, last_name, email, phone_number, password, role) VALUES 
('Uma', 'Abdi', 'uma1@gmail.com', '0722000000', '$2y$10$1YvBeMq4Ot4OIzluMOkL8eSPlDm/vf1RvJDhD/S94gnKL7hVgKHx2', 'PASSENGER'),
('Vin', 'Ndlovu', 'vin2@gmail.com', '0722000001', '$2y$10$NHV5qfiqIxq8CX08oMIAzu1HUU1aAzAg/VeCszLban9to86DGxr7O', 'PASSENGER'),
('Will', 'Chamele', 'will3@gmail.com', '0722000002', '$2y$10$isNOgS0qXW3/jaKOHK/5aeMDajNAnJPxU5NhcAzUdRPr5NzdSReiu', 'PASSENGER'),
('Xena', 'Tesfaye', 'xena4@gmail.com', '0722000003', '$2y$10$KY1KRlHaK7fU.fPjWQzrGehf4EtXzqD6cZKOU55Ysbwwv9ojHR3Fi', 'PASSENGER'),
('Yara', 'Mensah', 'yara5@gmail.com', '0722000004', '$2y$10$/cYOmtVIWUga.v0oLa6kEukgJT922bVzTMjCmkLuuBLK6WlPUC6Fi', 'PASSENGER'),
('Zac', 'Diallo', 'zac6@gmail.com', '0722000005', '$2y$10$uI27jAHOQfMptYojSuWiQ.U/ZrbkbPRZsk8wG0IQr8CXWljPEWGv2', 'PASSENGER'),
('Adam', 'Keita', 'adam7@gmail.com', '0722000006', '$2y$10$cKzfWlu7dfxQaVZ9h4YdOumimgSVLp8isYQzHvspOMom9.RUuUAhG', 'PASSENGER'),
('Bella', 'Sow', 'bella8@gmail.com', '0722000007', '$2y$10$CE03fm6meXEWMKeL48fXsunPESkwcP.krgkbZSUDv.v2.YMioHu6q', 'PASSENGER'),
('Chris', 'Traore', 'chris9@gmail.com', '0722000008', '$2y$10$J/xI66qvwJoFOei8mACNSueIhH9xVv6va7E.4tgaolFxQLyx86xvW', 'PASSENGER'),
('Drake', 'Kone', 'drake10@gmail.com', '0722000009', '$2y$10$FjK8MDssTU5GMnetQ9FAIe1NIK/yi0JNY7bIbqAoxi2i9MouNqxfS', 'PASSENGER');

-- --- INSERT DRIVERS ---
INSERT INTO drivers (national_id, full_name, phone, email) VALUES 
('ID00000001', 'John Mwangi', '0733000000', 'john.mwangi@gmail.com'),
('ID00000002', 'Samuel Okello', '0733000001', 'samuel.okello@gmail.com'),
('ID00000003', 'David Mengistu', '0733000002', 'david.mengistu@gmail.com'),
('ID00000004', 'Mohammed Hassan', '0733000003', 'mohammed.hassan@gmail.com'),
('ID00000005', 'Peter Kamau', '0733000004', 'peter.kamau@gmail.com'),
('ID00000006', 'James Omondi', '0733000005', 'james.omondi@gmail.com'),
('ID00000007', 'Benson Kiprop', '0733000006', 'benson.kiprop@gmail.com'),
('ID00000008', 'Charles Odhiambo', '0733000007', 'charles.odhiambo@gmail.com'),
('ID00000009', 'Joseph Kariuki', '0733000008', 'joseph.kariuki@gmail.com'),
('ID00000010', 'Thomas Njoroge', '0733000009', 'thomas.njoroge@gmail.com'),
('ID00000011', 'Emmanuel Abebe', '0733000010', 'emmanuel.abebe@gmail.com'),
('ID00000012', 'Isaac Tesfaye', '0733000011', 'isaac.tesfaye@gmail.com'),
('ID00000013', 'Gabriel Selassie', '0733000012', 'gabriel.selassie@gmail.com'),
('ID00000014', 'Michael Afewerki', '0733000013', 'michael.afewerki@gmail.com'),
('ID00000015', 'Daniel Tekle', '0733000014', 'daniel.tekle@gmail.com'),
('ID00000016', 'Richard Mwanza', '0733000015', 'richard.mwanza@gmail.com'),
('ID00000017', 'Patrick Mutua', '0733000016', 'patrick.mutua@gmail.com'),
('ID00000018', 'Stephen Musyoka', '0733000017', 'stephen.musyoka@gmail.com'),
('ID00000019', 'George Otieno', '0733000018', 'george.otieno@gmail.com'),
('ID00000020', 'Edward Wanyama', '0733000019', 'edward.wanyama@gmail.com'),
('ID00000021', 'Brian Kibet', '0733000020', 'brian.kibet@gmail.com'),
('ID00000022', 'Kevin Cheruiyot', '0733000021', 'kevin.cheruiyot@gmail.com'),
('ID00000023', 'Dennis Kemboi', '0733000022', 'dennis.kemboi@gmail.com'),
('ID00000024', 'Alex Rotich', '0733000023', 'alex.rotich@gmail.com'),
('ID00000025', 'Felix Langat', '0733000024', 'felix.langat@gmail.com'),
('ID00000026', 'Victor Ochieng', '0733000025', 'victor.ochieng@gmail.com'),
('ID00000027', 'Collins Okeyo', '0733000026', 'collins.okeyo@gmail.com'),
('ID00000028', 'Fredrick Owino', '0733000027', 'fredrick.owino@gmail.com'),
('ID00000029', 'Walter Aketch', '0733000028', 'walter.aketch@gmail.com'),
('ID00000030', 'Moses Odongo', '0733000029', 'moses.odongo@gmail.com');

-- --- INSERT BUSES ---
INSERT INTO buses (reg_no, bus_name, max_passengers, seat_layout, driver_id) VALUES 
('KWI 435Z', 'Wema Executive 1', 40, '2x2', 1),
('KIP 893K', 'Wema Executive 2', 40, '2x2', 2),
('KHN 719W', 'Wema Executive 3', 40, '2x2', 3),
('KOY 346P', 'Wema Executive 4', 40, '2x2', 4),
('UPP 520A', 'Wema Executive 5', 40, '2x2', 5),
('UUH 503W', 'Wema Executive 6', 40, '2x2', 6),
('T 435 VWM', 'Wema Executive 7', 40, '2x2', 7),
('T 155 UII', 'Wema Executive 8', 40, '2x2', 8),
('RLR 718 H', 'Wema Executive 9', 40, '2x2', 9),
('SIJ 854 GP', 'Wema Executive 10', 40, '2x2', 10),
('KJI 112Z', 'Wema Executive 11', 40, '2x2', 11),
('KOT 120F', 'Wema Executive 12', 40, '2x2', 12),
('KJX 893M', 'Wema Executive 13', 40, '2x2', 13),
('KAL 785Y', 'Wema Executive 14', 40, '2x2', 14),
('UAP 465F', 'Wema Executive 15', 40, '2x2', 15),
('UTK 299E', 'Wema Executive 16', 40, '2x2', 16),
('T 175 CCH', 'Wema Executive 17', 40, '2x2', 17),
('T 676 VKM', 'Wema Executive 18', 40, '2x2', 18),
('RQI 605 S', 'Wema Executive 19', 40, '2x2', 19),
('ENM 318 GP', 'Wema Executive 20', 40, '2x2', 20),
('KHJ 537G', 'Wema Executive 21', 40, '2x2', 21),
('KZQ 699X', 'Wema Executive 22', 40, '2x2', 22),
('KUI 133D', 'Wema Executive 23', 40, '2x2', 23),
('KIS 653J', 'Wema Executive 24', 40, '2x2', 24),
('UIH 545W', 'Wema Executive 25', 40, '2x2', 25),
('UOF 319L', 'Wema Executive 26', 40, '2x2', 26),
('T 788 UOC', 'Wema Executive 27', 40, '2x2', 27),
('T 909 NSY', 'Wema Executive 28', 40, '2x2', 28),
('RFA 598 Q', 'Wema Executive 29', 40, '2x2', 29),
('YET 839 GP', 'Wema Executive 30', 40, '2x2', 30);

-- --- INSERT ROUTES (International) ---
INSERT INTO routes (from_location, to_location, departure_date, departure_time, cost, bus_id) VALUES 
('Nairobi, Kenya', 'Kampala, Uganda', '2026-04-07', '12:00:00', 3500, 1),
('Kampala, Uganda', 'Nairobi, Kenya', '2026-06-14', '15:10:00', 3500, 2),
('Nairobi, Kenya', 'Arusha, Tanzania', '2026-11-25', '14:10:00', 2500, 3),
('Arusha, Tanzania', 'Nairobi, Kenya', '2026-09-20', '20:40:00', 2500, 4),
('Johannesburg, SA', 'Asmara, Eritrea', '2026-05-22', '13:30:00', 25000, 5),
('Mombasa, Kenya', 'Dar es Salaam, Tanzania', '2026-10-05', '17:40:00', 4000, 6),
('Kigali, Rwanda', 'Kampala, Uganda', '2026-11-03', '13:40:00', 2000, 7),
('Bujumbura, Burundi', 'Kigali, Rwanda', '2026-03-18', '14:10:00', 1500, 8),
('Addis Ababa, Ethiopia', 'Nairobi, Kenya', '2026-08-18', '20:00:00', 6000, 9),
('Lusaka, Zambia', 'Dar es Salaam, Tanzania', '2026-06-12', '12:40:00', 8000, 10),
('Nairobi, Kenya', 'Kampala, Uganda', '2026-11-15', '07:10:00', 3500, 11),
('Kampala, Uganda', 'Nairobi, Kenya', '2026-09-01', '10:40:00', 3500, 12),
('Nairobi, Kenya', 'Arusha, Tanzania', '2026-10-05', '17:10:00', 2500, 13),
('Arusha, Tanzania', 'Nairobi, Kenya', '2026-01-16', '20:20:00', 2500, 14),
('Johannesburg, SA', 'Asmara, Eritrea', '2026-05-25', '10:40:00', 25000, 15),
('Mombasa, Kenya', 'Dar es Salaam, Tanzania', '2026-01-20', '20:10:00', 4000, 16),
('Kigali, Rwanda', 'Kampala, Uganda', '2026-04-07', '06:50:00', 2000, 17),
('Bujumbura, Burundi', 'Kigali, Rwanda', '2026-03-26', '06:50:00', 1500, 18),
('Addis Ababa, Ethiopia', 'Nairobi, Kenya', '2026-10-26', '10:20:00', 6000, 19),
('Lusaka, Zambia', 'Dar es Salaam, Tanzania', '2026-04-12', '15:10:00', 8000, 20),
('Nairobi, Kenya', 'Kampala, Uganda', '2026-09-26', '17:20:00', 3500, 21),
('Kampala, Uganda', 'Nairobi, Kenya', '2026-10-24', '16:10:00', 3500, 22),
('Nairobi, Kenya', 'Arusha, Tanzania', '2026-09-05', '09:30:00', 2500, 23),
('Arusha, Tanzania', 'Nairobi, Kenya', '2026-11-04', '09:10:00', 2500, 24),
('Johannesburg, SA', 'Asmara, Eritrea', '2026-08-01', '18:10:00', 25000, 25),
('Mombasa, Kenya', 'Dar es Salaam, Tanzania', '2026-09-09', '08:30:00', 4000, 26),
('Kigali, Rwanda', 'Kampala, Uganda', '2026-09-11', '20:40:00', 2000, 27),
('Bujumbura, Burundi', 'Kigali, Rwanda', '2026-12-07', '20:30:00', 1500, 28),
('Addis Ababa, Ethiopia', 'Nairobi, Kenya', '2026-08-11', '12:20:00', 6000, 29),
('Lusaka, Zambia', 'Dar es Salaam, Tanzania', '2026-06-20', '10:50:00', 8000, 30);

-- --- INSERT BOOKINGS ---
INSERT INTO bookings (booking_time, seat_number, booking_status, qr_token, user_id, route_id, bus_id) VALUES 
('2026-06-05 20:00:00', '2A', 'PAID', 'e6233292db93c159fca80cd558ffbfd9', 22, 2, 2),
('2026-10-03 15:00:00', '3A', 'PAID', '0db1515fc46edd6e578051bcd29375b6', 23, 3, 3),
('2026-02-16 20:00:00', '4A', 'PAID', '730e6e438d5f966a527f4f538f132003', 24, 4, 4),
('2026-04-26 14:00:00', '5A', 'PAID', '66fc8bc02fd8ac40242e137f1830bfb9', 25, 5, 5),
('2026-03-27 12:00:00', '6A', 'PAID', '622d6ca0678c67e7fdd6a7d368465fa4', 26, 6, 6),
('2026-02-04 13:00:00', '7A', 'PAID', '26f3029aeed588071f58b38de5757653', 27, 7, 7),
('2026-09-05 20:00:00', '8A', 'PAID', 'dc5486d63381738a637789a92b8085fa', 28, 8, 8),
('2026-04-20 16:00:00', '9A', 'PAID', '71b059ece856b4830ff8068af95eec29', 29, 9, 9),
('2026-06-05 15:00:00', '10A', 'PAID', '4477b9b52f1ae4f00c21a4ea55af147a', 30, 10, 10),
('2026-12-24 10:00:00', '11A', 'PAID', '8a51b1f62ed3c7abd8fd96a67b744c63', 21, 11, 11),
('2026-07-03 19:00:00', '12A', 'PAID', 'eabec05090e648641aca30b6dc9dde54', 22, 12, 12),
('2026-09-18 09:00:00', '13A', 'PAID', '0688f64043a983e55793317de1d00730', 23, 13, 13),
('2026-06-20 14:00:00', '14A', 'PAID', '61d1e57c0708a4edc51066ae81067bac', 24, 14, 14),
('2026-06-19 17:00:00', '15A', 'PAID', '0d5ba3994aa82106ff5e852aa841f395', 25, 15, 15),
('2026-04-14 08:00:00', '16A', 'PAID', '52a4dd281e934256937909057dad588c', 26, 16, 16),
('2026-11-11 12:00:00', '17A', 'PAID', '32fe983757e7eb28580a7a519bc5cd7a', 27, 17, 17),
('2026-01-11 10:00:00', '18A', 'PAID', '373db2a35abc3e3b8b1f6a9eaf88b9bf', 28, 18, 18),
('2026-08-20 19:00:00', '19A', 'PAID', '31400a08f0666ae9067b670816f3a7b7', 29, 19, 19),
('2026-06-01 08:00:00', '20A', 'PAID', '747d0627ee743985911357a1bb6c2185', 30, 20, 20),
('2026-07-14 16:00:00', '21A', 'PAID', 'da61c9e0d991ec6df279d64349ac43b8', 21, 21, 21),
('2026-06-22 14:00:00', '22A', 'PAID', '8d9c0cd02e567801f2a89bcdbd17a720', 22, 22, 22),
('2026-08-24 12:00:00', '23A', 'PAID', '99ac1e189752a4d8b44304de6cd6bbe9', 23, 23, 23),
('2026-07-22 14:00:00', '24A', 'PAID', '98cd95edd59baf6a2333c93be1ecd4b8', 24, 24, 24),
('2026-11-18 14:00:00', '25A', 'PAID', '7c100301a8e2ff2b11e6df1d95730ba5', 25, 25, 25),
('2026-01-05 17:00:00', '26A', 'PAID', '149cf7b391f41ebd4e0151b3c1619c62', 26, 26, 26),
('2026-06-23 16:00:00', '27A', 'PAID', '46f3d5ae88f84387aa08bdf6afd424ed', 27, 27, 27),
('2026-10-01 11:00:00', '28A', 'PAID', 'a23cc6ba5f5ab6e6b4d1d044f30a245d', 28, 28, 28),
('2026-08-04 08:00:00', '29A', 'PAID', '7f89ebecb0dc36b7d2f55fd2480667e1', 29, 29, 29),
('2026-04-21 13:00:00', '30A', 'PAID', '5095b52c5c74e2c358469a1b4fd6755b', 30, 30, 30),
('2026-09-19 14:00:00', '31A', 'PAID', 'e6b951a4a4eb2d2543f08052046565d1', 21, 1, 1);

-- --- INSERT FEEDBACK ---
INSERT INTO feedback (rating, comments, feedback_date, user_id, bus_id, route_id) VALUES 
(4, 'Charging ports were not working, please fix.', '2026-12-11', 22, 2, 2),
(3, 'Charging ports were not working, please fix.', '2026-08-04', 23, 3, 3),
(5, 'Great service, very comfortable bus.', '2026-03-25', 24, 4, 4),
(4, 'Love the new buses, very modern and fresh.', '2026-12-25', 25, 5, 5),
(5, 'Bus was a bit late but the ride was okay.', '2026-02-08', 26, 6, 6),
(5, 'Excellent staff and safe driving. Will book again.', '2026-07-17', 27, 7, 7),
(5, 'The driver drove carefully, I felt safe throughout.', '2026-06-02', 28, 8, 8),
(5, 'Best travel experience I have had in a long time.', '2026-06-28', 29, 9, 9),
(5, 'Excellent staff and safe driving. Will book again.', '2026-09-26', 30, 10, 10),
(3, 'Enjoyed the free Wi-Fi, it was surprisingly fast.', '2026-08-09', 21, 11, 11),
(3, 'The snacks provided were a nice touch.', '2026-09-17', 22, 12, 12),
(5, 'Great service, very comfortable bus.', '2026-07-18', 23, 13, 13),
(4, 'Enjoyed the free Wi-Fi, it was surprisingly fast.', '2026-03-17', 24, 14, 14),
(3, 'Too many stops along the way made the trip longer.', '2026-03-13', 25, 15, 15),
(3, 'Booking process was easy and the bus was on time.', '2026-04-11', 26, 16, 16),
(3, 'Too many stops along the way made the trip longer.', '2026-01-15', 27, 17, 17),
(5, 'The bus was noisy, could not sleep well.', '2026-09-15', 28, 18, 18),
(5, 'Booking process was easy and the bus was on time.', '2026-04-16', 29, 19, 19),
(5, 'Bus was a bit late but the ride was okay.', '2026-07-14', 30, 20, 20),
(3, 'Booking process was easy and the bus was on time.', '2026-03-27', 21, 21, 21),
(5, 'Excellent staff and safe driving. Will book again.', '2026-01-11', 22, 22, 22),
(4, 'The journey was smooth and the driver was professional.', '2026-08-25', 23, 23, 23),
(3, 'Enjoyed the free Wi-Fi, it was surprisingly fast.', '2026-06-09', 24, 24, 24),
(4, 'Customer service was helpful when I needed to change my seat.', '2026-02-18', 25, 25, 25),
(5, 'Great service, very comfortable bus.', '2026-04-05', 26, 26, 26),
(4, 'The bus was noisy, could not sleep well.', '2026-12-26', 27, 27, 27),
(4, 'Bus was a bit late but the ride was okay.', '2026-10-01', 28, 28, 28),
(5, 'The journey was smooth and the driver was professional.', '2026-07-06', 29, 29, 29),
(3, 'Arrived at the destination ahead of schedule!', '2026-06-20', 30, 30, 30),
(4, 'Love the new buses, very modern and fresh.', '2026-07-26', 21, 1, 1);

